name: Prepare Release

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run prepare release script
      run: |
        export MY_POM_VERSION=`./mvnw -q -Dexec.executable="echo" -Dexec.args='${projects.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`
        echo "POM VERSION" ${MY_POM_VERSION}
        if [[ $MY_POM_VERSION =~ ^.*SNAPSHOT$ ]];
        then
            . ./CI/release.sh
        else
            echo "not releasing release version: " ${MY_POM_VERSION}
        fi
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        GH_USER: ${{ secrets.GITHUB_USER }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_CRED_64: ${{ secrets.GH_CRED_64 }}

