name: Prepare_Release

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run prepare release script
      run: |
        echo "GH_USER" ${GH_USER}
        echo "GITHUB_USER" ${GITHUB_USER}
        echo "SC_TEST" ${SC_TEST}
        export MY_POM_VERSION=`./mvnw -q -Dexec.executable="echo" -Dexec.args='${projects.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`
        echo "POM VERSION" ${MY_POM_VERSION}
        if [[ $MY_POM_VERSION =~ ^.*SNAPSHOT$ ]];
        then
           . ./CI/prepare-release.sh
        else
            echo "not preparing release for release version: " ${MY_POM_VERSION}
        fi
    - name: test variables
      run: |
        echo "TEST GH_USER" ${GH_USER}
        echo "TEST GITHUB_USER" ${GITHUB_USER}
        echo "TEST SC_TEST" ${SC_TEST}
        echo "TEST SC_VERSION" ${SC_VERSION}
        echo "TEST SC_NEXT_VERSION" ${SC_NEXT_VERSION}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: prepare release $SC_VERSION
        title: 'prepare release $SC_VERSION'
        branch: prepare-release-$SC_VERSION
    env:
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      GH_USER: ${{ secrets.GH_USER }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USER: ${{ secrets.GITHUB_USER }}
      SC_TEST: ${{ secrets.SC_TEST }}
      GH_CRED_64: ${{ secrets.GH_CRED_64 }}
      SC_VERSION:
      SC_NEXT_VERSION:

