name: Release

on:
  workflow_dispatch:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up Gradle credentials
      run: |
        mkdir -p ~/.gradle
        echo "gradle.publish.key=$GRADLE_PUBLISH_KEY\ngradle.publish.secret=$GRADLE_PUBLISH_SECRET" > ~/.gradle/gradle.properties
    - name: Run pre release script
      id: preRelease
      run: |
        # export GPG_TTY=$(tty)
        export MY_POM_VERSION=`./mvnw -q -Dexec.executable="echo" -Dexec.args='${projects.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`
        if [[ $MY_POM_VERSION =~ ^.*SNAPSHOT$ ]];
        then
          echo "not releasing snapshot version: " ${MY_POM_VERSION}
          echo "::set-env name=RELEASE_OK::no"
        else
          . ./CI/pre-release.sh
          echo "::set-env name=RELEASE_OK::yes"
        fi
        echo "::set-env name=SC_VERSION::$SC_VERSION"
        echo "::set-env name=SC_NEXT_VERSION::$SC_NEXT_VERSION"
    - name: configure git user email
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git config --global hub.protocol https
        git remote set-url origin https://\${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/''' + 'frantuma/nagger-core' + '''.git
    - name: Run maven deploy/release (action-maven-publish)
      uses: samuelmeuli/action-maven-publish@v1
      if: env.RELEASE_OK == 'yes'
      with:
        gpg_private_key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY_NO_ESCAPE }}
        gpg_passphrase: ${{ secrets.OSSRH_GPG_PRIVATE_PASSPHRASE }}
        nexus_username: ${{ secrets.OSSRH_USERNAME }}
        nexus_password: ${{ secrets.OSSRH_TOKEN }}
        maven_profiles: "release"
    - name: Run post release script
      id: postRelease
      if: env.RELEASE_OK == 'yes'
      run: |
        . ./CI/post-release.sh
    - name: Create Next Snapshot Pull Request
      uses: peter-evans/create-pull-request@v2
      if: env.RELEASE_OK == 'yes'
      with:
        token: ${{ steps.generate-token.outputs.token }}
        commit-message: bump snapshot ${{ env.SC_NEXT_VERSION }}-SNAPSHOT
        title: 'bump snapshot ${{ env.SC_NEXT_VERSION }}-SNAPSHOT'
        branch: bump-snap-${{ env.SC_NEXT_VERSION }}-SNAPSHOT
    - name: Update V1 Readme
      id: updateV1Readme
      if: env.RELEASE_OK == 'yes'
      run: |
        . ./CI/trigger-updateV1Readme-Action.sh ${{ env.SC_VERSION }} ${{ env.SC_NEXT_VERSION }}

    env:
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      GH_USER: ${{ secrets.GH_USER }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USER: ${{ secrets.GITHUB_USER }}
      SC_TEST: ${{ secrets.SC_TEST }}
      GH_CRED_64: ${{ secrets.GH_CRED_64 }}
      SC_VERSION:
      SC_NEXT_VERSION:
      GPG_PRIVATE_KEY: ${{ secrets.OSSRH_GPG_PRIVATE_KEY_NO_ESCAPE }}
      GPG_PRIVATE_KEY_ESCAPE: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PRIVATE_PASSPHRASE }}
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
