name: Test

on:
  workflow_dispatch:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Gradle credentials
      run: |
        echo "one ${{ secrets.GITHUB_USER }}"
        echo "two ${{ secrets.GH_USER }}"
